import * as db from "./db";

async function main() {
  console.log("\n[Seed Extended] Creating extended test data...");
  console.log("3 Corporations × 3 Companies × 3 Contacts + 2 Companies × 2 Contacts\n");

  // Corporation 1: SAP SE
  const corp1 = {
    name: "SAP SE",
    headquartersCountry: "DE",
    totalRevenueEur: 31200000000,
    industry: "Software & IT",
    website: "https://www.sap.com",
    linkedinUrl: "https://linkedin.com/company/sap",
    status: "Customer",
    priority: "High",
    companySize: "10000+",
    stage: "Producer",
    notes: null,
    products: "ERP, Cloud Solutions, Analytics",
    targetMarkets: "Enterprise Software, Cloud",
    countries: "DE, US, CN, IN",
    referenceCustomers: null,
    employeeCount: 107000,
    international: true,
    profileAnalyzedAt: null,
    scoutStatus: "Analyzed",
    scoutGeneration: 0,
    scoutParentId: null,
    discoveryMethod: "Manual",
    discoveredAt: new Date(),
  };

  const corp1Result = await db.createCorporation(corp1);
  const corp1Id = corp1Result.id;
  console.log(`[Seed] Created corporation: ${corp1.name} (ID: ${corp1Id})`);

  // SAP Companies
  const sapCompanies = [
    {
      corporationId: corp1Id,
      name: "SAP Deutschland SE & Co. KG",
      country: "DE",
      city: "Walldorf",
      address: "Dietmar-Hopp-Allee 16",
      employeeCount: 25000,
      revenueEur: 8000000000,
      website: "https://www.sap.com/germany",
      legalForm: "SE & Co. KG",
      notes: null,
      products: null,
    },
    {
      corporationId: corp1Id,
      name: "SAP Labs Berlin",
      country: "DE",
      city: "Berlin",
      address: "Rosenthaler Str. 30",
      employeeCount: 1500,
      revenueEur: null,
      website: "https://www.sap.com/berlin",
      legalForm: "GmbH",
      notes: null,
      products: null,
    },
    {
      corporationId: corp1Id,
      name: "SAP Austria GmbH",
      country: "AT",
      city: "Wien",
      address: "Lassallestraße 7a",
      employeeCount: 800,
      revenueEur: 500000000,
      website: "https://www.sap.com/austria",
      legalForm: "GmbH",
      notes: null,
      products: null,
    },
  ];

  const sapCompanyIds: string[] = [];
  for (const company of sapCompanies) {
    const result = await db.createCompany(company);
    const companyId = result[0].insertId.toString();
    sapCompanyIds.push(companyId);
    console.log(`  [Seed] Created company: ${company.name} (ID: ${companyId})`);
  }

  // SAP Contacts (3 per company)
  const sapContacts = [
    // Company 1 contacts
    [
      {
        contact: {
          firstName: "Stefan",
          lastName: "Klein",
          phone: "+49 6227 7-47474",
          mobile: "+49 170 1234567",
          jobTitle: "CTO",
          department: "Technology",
          function: "Technology",
          linkedinUrl: "https://linkedin.com/in/stefan-klein-sap",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 6227 7-47474",
          phoneMobile: "+49 170 1234567",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "stefan.klein@sap.com",
        position: "CTO",
      },
      {
        contact: {
          firstName: "Julia",
          lastName: "Becker",
          phone: "+49 6227 7-48000",
          mobile: null,
          jobTitle: "Head of Sales",
          department: "Sales",
          function: "Sales",
          linkedinUrl: "https://linkedin.com/in/julia-becker-sap",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 6227 7-48000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "julia.becker@sap.com",
        position: "Head of Sales",
      },
      {
        contact: {
          firstName: "Martin",
          lastName: "Hoffmann",
          phone: "+49 6227 7-49000",
          mobile: "+49 171 2345678",
          jobTitle: "Product Manager",
          department: "Product",
          function: "Product Management",
          linkedinUrl: "https://linkedin.com/in/martin-hoffmann-sap",
          contactStatus: "Warm",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 6227 7-49000",
          phoneMobile: "+49 171 2345678",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "martin.hoffmann@sap.com",
        position: "Product Manager",
      },
    ],
    // Company 2 contacts
    [
      {
        contact: {
          firstName: "Laura",
          lastName: "Fischer",
          phone: "+49 30 2000-5000",
          mobile: null,
          jobTitle: "Innovation Lead",
          department: "R&D",
          function: "Research",
          linkedinUrl: "https://linkedin.com/in/laura-fischer-sap",
          contactStatus: "Warm",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 2000-5000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "laura.fischer@sap.com",
        position: "Innovation Lead",
      },
      {
        contact: {
          firstName: "David",
          lastName: "Richter",
          phone: "+49 30 2000-5100",
          mobile: "+49 172 3456789",
          jobTitle: "Senior Developer",
          department: "Engineering",
          function: "Engineering",
          linkedinUrl: "https://linkedin.com/in/david-richter-sap",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 2000-5100",
          phoneMobile: "+49 172 3456789",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "david.richter@sap.com",
        position: "Senior Developer",
      },
      {
        contact: {
          firstName: "Sophie",
          lastName: "Neumann",
          phone: "+49 30 2000-5200",
          mobile: null,
          jobTitle: "UX Designer",
          department: "Design",
          function: "Design",
          linkedinUrl: "https://linkedin.com/in/sophie-neumann-sap",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 2000-5200",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "sophie.neumann@sap.com",
        position: "UX Designer",
      },
    ],
    // Company 3 contacts
    [
      {
        contact: {
          firstName: "Andreas",
          lastName: "Gruber",
          phone: "+43 1 28844-0",
          mobile: "+43 664 1234567",
          jobTitle: "Country Manager Austria",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/andreas-gruber-sap",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 1 28844-0",
          phoneMobile: "+43 664 1234567",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "andreas.gruber@sap.com",
        position: "Country Manager Austria",
      },
      {
        contact: {
          firstName: "Christina",
          lastName: "Berger",
          phone: "+43 1 28844-100",
          mobile: null,
          jobTitle: "Sales Director",
          department: "Sales",
          function: "Sales",
          linkedinUrl: "https://linkedin.com/in/christina-berger-sap",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 1 28844-100",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "christina.berger@sap.com",
        position: "Sales Director",
      },
      {
        contact: {
          firstName: "Michael",
          lastName: "Steiner",
          phone: "+43 1 28844-200",
          mobile: "+43 664 2345678",
          jobTitle: "Consultant",
          department: "Consulting",
          function: "Consulting",
          linkedinUrl: "https://linkedin.com/in/michael-steiner-sap",
          contactStatus: "Warm",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 1 28844-200",
          phoneMobile: "+43 664 2345678",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "michael.steiner@sap.com",
        position: "Consultant",
      },
    ],
  ];

  for (let i = 0; i < sapContacts.length; i++) {
    for (const contactData of sapContacts[i]) {
      await db.createContact(contactData.contact, sapCompanyIds[i], contactData.email, contactData.position);
      console.log(`    [Seed] Created contact: ${contactData.contact.firstName} ${contactData.contact.lastName}`);
    }
  }

  // Corporation 2: Volkswagen AG
  const corp2 = {
    name: "Volkswagen AG",
    headquartersCountry: "DE",
    totalRevenueEur: 279200000000,
    industry: "Automotive",
    website: "https://www.volkswagen.de",
    linkedinUrl: "https://linkedin.com/company/volkswagen",
    status: "Target",
    priority: "High",
    companySize: "10000+",
    stage: "Producer",
    notes: null,
    products: "Automobiles, Commercial Vehicles, Electric Vehicles",
    targetMarkets: "Automotive, E-Mobility",
    countries: "DE, CN, US, BR",
    referenceCustomers: null,
    employeeCount: 675000,
    international: true,
    profileAnalyzedAt: null,
    scoutStatus: "Analyzed",
    scoutGeneration: 0,
    scoutParentId: null,
    discoveryMethod: "Manual",
    discoveredAt: new Date(),
  };

  const corp2Result = await db.createCorporation(corp2);
  const corp2Id = corp2Result.id;
  console.log(`\n[Seed] Created corporation: ${corp2.name} (ID: ${corp2Id})`);

  // VW Companies
  const vwCompanies = [
    {
      corporationId: corp2Id,
      name: "Volkswagen AG Wolfsburg",
      country: "DE",
      city: "Wolfsburg",
      address: "Berliner Ring 2",
      employeeCount: 60000,
      revenueEur: 100000000000,
      website: "https://www.volkswagen.de",
      legalForm: "AG",
      notes: null,
      products: null,
    },
    {
      corporationId: corp2Id,
      name: "Audi AG",
      country: "DE",
      city: "Ingolstadt",
      address: "Auto-Union-Straße 1",
      employeeCount: 90000,
      revenueEur: 61800000000,
      website: "https://www.audi.de",
      legalForm: "AG",
      notes: null,
      products: null,
    },
    {
      corporationId: corp2Id,
      name: "Porsche AG",
      country: "DE",
      city: "Stuttgart",
      address: "Porscheplatz 1",
      employeeCount: 38000,
      revenueEur: 40500000000,
      website: "https://www.porsche.com",
      legalForm: "AG",
      notes: null,
      products: null,
    },
  ];

  const vwCompanyIds: string[] = [];
  for (const company of vwCompanies) {
    const result = await db.createCompany(company);
    const companyId = result[0].insertId.toString();
    vwCompanyIds.push(companyId);
    console.log(`  [Seed] Created company: ${company.name} (ID: ${companyId})`);
  }

  // VW Contacts (3 per company)
  const vwContacts = [
    // VW Wolfsburg
    [
      {
        contact: {
          firstName: "Oliver",
          lastName: "Blume",
          phone: "+49 5361 9-0",
          mobile: null,
          jobTitle: "CEO",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/oliver-blume-vw",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 5361 9-0",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "oliver.blume@volkswagen.de",
        position: "CEO",
      },
      {
        contact: {
          firstName: "Petra",
          lastName: "Wagner",
          phone: "+49 5361 9-1000",
          mobile: "+49 173 4567890",
          jobTitle: "Head of Procurement",
          department: "Procurement",
          function: "Procurement",
          linkedinUrl: "https://linkedin.com/in/petra-wagner-vw",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 5361 9-1000",
          phoneMobile: "+49 173 4567890",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "petra.wagner@volkswagen.de",
        position: "Head of Procurement",
      },
      {
        contact: {
          firstName: "Klaus",
          lastName: "Zimmermann",
          phone: "+49 5361 9-2000",
          mobile: null,
          jobTitle: "Production Manager",
          department: "Production",
          function: "Production",
          linkedinUrl: "https://linkedin.com/in/klaus-zimmermann-vw",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 5361 9-2000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "klaus.zimmermann@volkswagen.de",
        position: "Production Manager",
      },
    ],
    // Audi
    [
      {
        contact: {
          firstName: "Markus",
          lastName: "Duesmann",
          phone: "+49 841 89-0",
          mobile: null,
          jobTitle: "CEO Audi",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/markus-duesmann-audi",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 841 89-0",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "markus.duesmann@audi.de",
        position: "CEO Audi",
      },
      {
        contact: {
          firstName: "Sabine",
          lastName: "Krause",
          phone: "+49 841 89-1000",
          mobile: "+49 174 5678901",
          jobTitle: "Head of E-Mobility",
          department: "E-Mobility",
          function: "E-Mobility",
          linkedinUrl: "https://linkedin.com/in/sabine-krause-audi",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 841 89-1000",
          phoneMobile: "+49 174 5678901",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "sabine.krause@audi.de",
        position: "Head of E-Mobility",
      },
      {
        contact: {
          firstName: "Frank",
          lastName: "Lehmann",
          phone: "+49 841 89-2000",
          mobile: null,
          jobTitle: "Quality Manager",
          department: "Quality",
          function: "Quality Management",
          linkedinUrl: "https://linkedin.com/in/frank-lehmann-audi",
          contactStatus: "Warm",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 841 89-2000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "frank.lehmann@audi.de",
        position: "Quality Manager",
      },
    ],
    // Porsche
    [
      {
        contact: {
          firstName: "Oliver",
          lastName: "Blume",
          phone: "+49 711 911-0",
          mobile: "+49 175 6789012",
          jobTitle: "CEO Porsche",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/oliver-blume-porsche",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 711 911-0",
          phoneMobile: "+49 175 6789012",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "oliver.blume@porsche.de",
        position: "CEO Porsche",
      },
      {
        contact: {
          firstName: "Barbara",
          lastName: "Frenkel",
          phone: "+49 711 911-1000",
          mobile: null,
          jobTitle: "Head of Procurement",
          department: "Procurement",
          function: "Procurement",
          linkedinUrl: "https://linkedin.com/in/barbara-frenkel-porsche",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 711 911-1000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "barbara.frenkel@porsche.de",
        position: "Head of Procurement",
      },
      {
        contact: {
          firstName: "Thomas",
          lastName: "Edig",
          phone: "+49 711 911-2000",
          mobile: "+49 176 7890123",
          jobTitle: "Vice President Sales",
          department: "Sales",
          function: "Sales",
          linkedinUrl: "https://linkedin.com/in/thomas-edig-porsche",
          contactStatus: "Warm",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 711 911-2000",
          phoneMobile: "+49 176 7890123",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "thomas.edig@porsche.de",
        position: "Vice President Sales",
      },
    ],
  ];

  for (let i = 0; i < vwContacts.length; i++) {
    for (const contactData of vwContacts[i]) {
      await db.createContact(contactData.contact, vwCompanyIds[i], contactData.email, contactData.position);
      console.log(`    [Seed] Created contact: ${contactData.contact.firstName} ${contactData.contact.lastName}`);
    }
  }

  // Corporation 3: Deutsche Telekom AG
  const corp3 = {
    name: "Deutsche Telekom AG",
    headquartersCountry: "DE",
    totalRevenueEur: 114400000000,
    industry: "Telecommunications",
    website: "https://www.telekom.com",
    linkedinUrl: "https://linkedin.com/company/deutsche-telekom",
    status: "Contacted",
    priority: "Medium",
    companySize: "10000+",
    stage: "Producer",
    notes: null,
    products: "Mobile, Fixed-line, Internet, Cloud",
    targetMarkets: "Telecommunications, Cloud Services",
    countries: "DE, US, PL, CZ",
    referenceCustomers: null,
    employeeCount: 216000,
    international: true,
    profileAnalyzedAt: null,
    scoutStatus: "Analyzed",
    scoutGeneration: 0,
    scoutParentId: null,
    discoveryMethod: "Manual",
    discoveredAt: new Date(),
  };

  const corp3Result = await db.createCorporation(corp3);
  const corp3Id = corp3Result.id;
  console.log(`\n[Seed] Created corporation: ${corp3.name} (ID: ${corp3Id})`);

  // Telekom Companies
  const telekomCompanies = [
    {
      corporationId: corp3Id,
      name: "Deutsche Telekom Deutschland GmbH",
      country: "DE",
      city: "Bonn",
      address: "Landgrabenweg 151",
      employeeCount: 80000,
      revenueEur: 45000000000,
      website: "https://www.telekom.de",
      legalForm: "GmbH",
      notes: null,
      products: null,
    },
    {
      corporationId: corp3Id,
      name: "T-Systems International GmbH",
      country: "DE",
      city: "Frankfurt",
      address: "Hahnstraße 43d",
      employeeCount: 28000,
      revenueEur: 4200000000,
      website: "https://www.t-systems.com",
      legalForm: "GmbH",
      notes: null,
      products: null,
    },
    {
      corporationId: corp3Id,
      name: "T-Mobile Austria GmbH",
      country: "AT",
      city: "Wien",
      address: "Rennweg 97-99",
      employeeCount: 3500,
      revenueEur: 1800000000,
      website: "https://www.t-mobile.at",
      legalForm: "GmbH",
      notes: null,
      products: null,
    },
  ];

  const telekomCompanyIds: string[] = [];
  for (const company of telekomCompanies) {
    const result = await db.createCompany(company);
    const companyId = result[0].insertId.toString();
    telekomCompanyIds.push(companyId);
    console.log(`  [Seed] Created company: ${company.name} (ID: ${companyId})`);
  }

  // Telekom Contacts (3 per company)
  const telekomContacts = [
    // Deutsche Telekom Deutschland
    [
      {
        contact: {
          firstName: "Timotheus",
          lastName: "Höttges",
          phone: "+49 228 181-0",
          mobile: null,
          jobTitle: "CEO",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/timotheus-hoettges",
          contactStatus: "Hot",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 228 181-0",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "timotheus.hoettges@telekom.de",
        position: "CEO",
      },
      {
        contact: {
          firstName: "Claudia",
          lastName: "Nemat",
          phone: "+49 228 181-1000",
          mobile: "+49 177 8901234",
          jobTitle: "Board Member Technology",
          department: "Technology",
          function: "Technology",
          linkedinUrl: "https://linkedin.com/in/claudia-nemat",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 228 181-1000",
          phoneMobile: "+49 177 8901234",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "claudia.nemat@telekom.de",
        position: "Board Member Technology",
      },
      {
        contact: {
          firstName: "Srini",
          lastName: "Gopalan",
          phone: "+49 228 181-2000",
          mobile: null,
          jobTitle: "CEO Germany",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/srini-gopalan",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 228 181-2000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "srini.gopalan@telekom.de",
        position: "CEO Germany",
      },
    ],
    // T-Systems
    [
      {
        contact: {
          firstName: "Adel",
          lastName: "Al-Saleh",
          phone: "+49 69 2000-0",
          mobile: null,
          jobTitle: "CEO T-Systems",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/adel-al-saleh",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 69 2000-0",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "adel.al-saleh@t-systems.com",
        position: "CEO T-Systems",
      },
      {
        contact: {
          firstName: "Peter",
          lastName: "Leukert",
          phone: "+49 69 2000-1000",
          mobile: "+49 178 9012345",
          jobTitle: "CIO",
          department: "IT",
          function: "IT",
          linkedinUrl: "https://linkedin.com/in/peter-leukert",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 69 2000-1000",
          phoneMobile: "+49 178 9012345",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "peter.leukert@t-systems.com",
        position: "CIO",
      },
      {
        contact: {
          firstName: "Sabine",
          lastName: "Bendiek",
          phone: "+49 69 2000-2000",
          mobile: null,
          jobTitle: "Chief Partner Officer",
          department: "Partnerships",
          function: "Partnerships",
          linkedinUrl: "https://linkedin.com/in/sabine-bendiek",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 69 2000-2000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "sabine.bendiek@t-systems.com",
        position: "Chief Partner Officer",
      },
    ],
    // T-Mobile Austria
    [
      {
        contact: {
          firstName: "Andreas",
          lastName: "Bierwirth",
          phone: "+43 676 2000",
          mobile: "+43 664 3456789",
          jobTitle: "CEO T-Mobile Austria",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/andreas-bierwirth",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 676 2000",
          phoneMobile: "+43 664 3456789",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "andreas.bierwirth@t-mobile.at",
        position: "CEO T-Mobile Austria",
      },
      {
        contact: {
          firstName: "Sonja",
          lastName: "Wallner",
          phone: "+43 676 2100",
          mobile: null,
          jobTitle: "Head of Marketing",
          department: "Marketing",
          function: "Marketing",
          linkedinUrl: "https://linkedin.com/in/sonja-wallner",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 676 2100",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "sonja.wallner@t-mobile.at",
        position: "Head of Marketing",
      },
      {
        contact: {
          firstName: "Robert",
          lastName: "Chvátal",
          phone: "+43 676 2200",
          mobile: "+43 664 4567890",
          jobTitle: "CTO",
          department: "Technology",
          function: "Technology",
          linkedinUrl: "https://linkedin.com/in/robert-chvatal",
          contactStatus: "Cold",
          decisionMaker: false,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+43 676 2200",
          phoneMobile: "+43 664 4567890",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "robert.chvatal@t-mobile.at",
        position: "CTO",
      },
    ],
  ];

  for (let i = 0; i < telekomContacts.length; i++) {
    for (const contactData of telekomContacts[i]) {
      await db.createContact(contactData.contact, telekomCompanyIds[i], contactData.email, contactData.position);
      console.log(`    [Seed] Created contact: ${contactData.contact.firstName} ${contactData.contact.lastName}`);
    }
  }

  // Additional 2 companies with 2 contacts each (no corporation)
  console.log("\n[Seed] Creating standalone companies...");

  const standaloneCompanies = [
    {
      corporationId: corp1Id, // Assign to SAP for now
      name: "Zalando SE",
      country: "DE",
      city: "Berlin",
      address: "Valeska-Gert-Straße 5",
      employeeCount: 17000,
      revenueEur: 10600000000,
      website: "https://www.zalando.de",
      legalForm: "SE",
      notes: null,
      products: null,
    },
    {
      corporationId: corp2Id, // Assign to VW for now
      name: "Delivery Hero SE",
      country: "DE",
      city: "Berlin",
      address: "Oranienburger Straße 70",
      employeeCount: 30000,
      revenueEur: 10100000000,
      website: "https://www.deliveryhero.com",
      legalForm: "SE",
      notes: null,
      products: null,
    },
  ];

  const standaloneCompanyIds: string[] = [];
  for (const company of standaloneCompanies) {
    const result = await db.createCompany(company);
    const companyId = result[0].insertId.toString();
    standaloneCompanyIds.push(companyId);
    console.log(`  [Seed] Created company: ${company.name} (ID: ${companyId})`);
  }

  // Standalone Contacts (2 per company)
  const standaloneContacts = [
    // Zalando
    [
      {
        contact: {
          firstName: "Robert",
          lastName: "Gentz",
          phone: "+49 30 2759-0",
          mobile: null,
          jobTitle: "Co-CEO",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/robert-gentz",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 2759-0",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "robert.gentz@zalando.de",
        position: "Co-CEO",
      },
      {
        contact: {
          firstName: "David",
          lastName: "Schneider",
          phone: "+49 30 2759-1000",
          mobile: "+49 179 0123456",
          jobTitle: "Co-CEO",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/david-schneider-zalando",
          contactStatus: "Warm",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 2759-1000",
          phoneMobile: "+49 179 0123456",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "david.schneider@zalando.de",
        position: "Co-CEO",
      },
    ],
    // Delivery Hero
    [
      {
        contact: {
          firstName: "Niklas",
          lastName: "Östberg",
          phone: "+49 30 5444-59000",
          mobile: null,
          jobTitle: "CEO",
          department: "Management",
          function: "Management",
          linkedinUrl: "https://linkedin.com/in/niklas-ostberg",
          contactStatus: "Cold",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 5444-59000",
          phoneMobile: null,
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "niklas.ostberg@deliveryhero.com",
        position: "CEO",
      },
      {
        contact: {
          firstName: "Emmanuel",
          lastName: "Thomassin",
          phone: "+49 30 5444-59100",
          mobile: "+49 180 1234567",
          jobTitle: "CFO",
          department: "Finance",
          function: "Finance",
          linkedinUrl: "https://linkedin.com/in/emmanuel-thomassin",
          contactStatus: "Cold",
          decisionMaker: true,
          companySize: null,
          responsiblePerson: null,
          category: null,
          tags: null,
          keyword1: null,
          keyword2: null,
          phoneBusiness: "+49 30 5444-59100",
          phoneMobile: "+49 180 1234567",
          phoneOffice: null,
          faxOffice: null,
          notes: null,
        },
        email: "emmanuel.thomassin@deliveryhero.com",
        position: "CFO",
      },
    ],
  ];

  for (let i = 0; i < standaloneContacts.length; i++) {
    for (const contactData of standaloneContacts[i]) {
      await db.createContact(contactData.contact, standaloneCompanyIds[i], contactData.email, contactData.position);
      console.log(`    [Seed] Created contact: ${contactData.contact.firstName} ${contactData.contact.lastName}`);
    }
  }

  console.log("\n[Seed Extended] Complete!");
  console.log("\n=== SUMMARY ===");
  console.log("3 Corporations:");
  console.log("  - SAP SE (3 companies, 9 contacts)");
  console.log("  - Volkswagen AG (3 companies, 9 contacts)");
  console.log("  - Deutsche Telekom AG (3 companies, 9 contacts)");
  console.log("2 Standalone Companies:");
  console.log("  - Zalando SE (2 contacts)");
  console.log("  - Delivery Hero SE (2 contacts)");
  console.log("\nTotal: 3 Corporations, 11 Companies, 31 Contacts");
  console.log("================\n");
}

main().catch(console.error);

